version: '3.8'
services:
  nextjs-app:
    build:
      context: .  # Build the image from the current directory (ap-dashboard)
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Map port 3001 to the host
    volumes:
      - .:/app  # Map the entire project to /app
      - /app/.next  # Explicitly map the .next directory to avoid permission issues
    environment:
      - NODE_ENV=development
    user: "1000:1000"  # Ensure the container runs as user 1000
